title: ぞうさんの森
description: パソコンや可愛い犬
theme: minima

lang: ja
timezone: Asia/Tokyo

header_pages:
  - index.md
  - about.md

minima:
  social_links:
    - platform: instagram
      user_url: https://www.instagram.com/mahamofumozoo/

instagram_username: mahamofumozoo


show_excerpts: true


excerpt_separator: "<!--more-->"
