title: ぞうさんの森
description: パソコンや可愛い犬
theme: minima

lang: ja
timezone: Asia/Tokyo

header_pages:
  - about.md

minima:
  social_links:
    - platform: instagram
      user_url: https://www.instagram.com/mahamofumozoo/


show_excerpts: true


excerpt_separator: "<!--more-->"
