title: ぞうさんの森
description: パソコンや可愛い犬
theme: minima

lang: ja
timezone: Asia/Tokyo

permalink: /posts/:year-:month-:day/:slug/

POST_IMG_DIR: /assets/img/posts
COMMON_IMG_DIR: /assets/img/common
POST_MEDIA_DIR: /assets/media/posts
COMMON_MEDIA_DIR: /assets/media/common

header_pages:
  - index.md
  - about.md

minima:
  social_links:
    - platform: instagram
      user_url: https://www.instagram.com/mahamofumozoo/

instagram_username: mahamofumozoo
twitter_username: regulate0558371


show_excerpts: true


excerpt_separator: "<!--more-->"
